camel:
  health:
    enabled: false
    indicator:
      enabled: true

  component:
    servlet:
      mapping:
        context-path: /camel/*

  service:
    lra:
      enabled: true
      coordinator-url: http://localhost:8080
      local-participant-url: http://localhost:8180/camel


# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
management:
  health:
    defaults:
      enabled: false
server:
  port: 8180

demo:
  stock-service-hostname: localhost
  stock-service-port: 8380
  order-service-hostname: localhost
  order-service-port: 8280

---
# ######################################
# Active configuration when deployed
spring:
  profiles: deployed
# ######################################
camel:
  service:
    lra:
      coordinator-url: http://localhost:8080
      local-participant-url: http://localhost:8080/camel
server:
  port: 8080

demo:
  stock-service-hostname: localhost
  stock-service-port: 8080
  order-service-hostname: localhost
  order-service-port: 8080
